spring:
  datasource:
    url: jdbc:mysql://80.211.137.250:3306/ogloszex
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ogloszex
    password: administrator@
  liquibase:
    contexts: prod